name: Build and Deploy to Google Cloud
on:
  push:
    branches: [ "main", "cloud" ]
env:
  PROJECT_ID: UMGRA
  GCLOUD_REGION: us-central1
  GCLOUD_REGISTRY: "${{ env.GCLOUD_REGION }}-docker.pkg.dev"
  IMAGE_TAG: "${{ env.GCLOUD_REGISTRY }}/${{ env.PROJECT_ID }}:${{ github.sha }}"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: google auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: container registry auth
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GCLOUD_REGISTRY }}
          password: ${{ steps.auth.outputs.access_token }}
          username: 'oauth2accesstoken'
      - name: build and push image
        run: |-
          docker build -t ${{ env.IMAGE_TAG }} ./
          docker push ${{ env.IMAGE_TAG }}
      - name: deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: 'server'
          region: ${{ env.GCLOUD_REGION }}
          image: ${{ env.IMAGE_TAG }}
      - name: output
        run: echo ${{ steps.deploy.outputs.url }}

